export const dataNavigation = [
  {
    id: "Cat1",
    name: "Danh mục cấp 1",
    icon: '<i class="ri-mail-line"></i>',
  },
  {
    id: "Cat2",
    name: "Danh mục cấp 2",
    icon: '<i class="ri-mail-add-line"></i>',
  },
  {
    id: "Cat3",
    name: "Danh mục cấp 3",
    icon: '<i class="ri-mail-star-line"></i>',
  },
  {
    id: "Cat4",
    name: "Danh sách bài viết",
    icon: '<i class="ri-markup-line"></i>',
  },
  {
    id: "Cat5",
    name: "Danh sách sản phẩm",
    icon: '<i class="ri-shapes-line"></i>',
  },
  {
    id: "Cat6",
    name: "Lịch hẹn",
    icon: '<i class="ri-calendar-2-line"></i>',
  },
  {
    id: "Cat7",
    name: "Bình luận",
    icon: '<i class="ri-chat-3-line"></i>',
  },
];

export const dataList = [
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
];

export const dataListAccount: iAccountAuth[] = [
  {
    id: 1,
    username: "admin1",
    password: "admin",
    fullName: "Nguyễn Văn A",
    email: "nva@gmail.com",
    phone: "0901234567",
    avatar: "",
    permission: "Bật",
    role: "guest",
    status: true,
  },
  {
    id: 2,
    username: "admin2",
    password: "admin",
    fullName: "Nguyễn Văn B",
    email: "nvb@gmail.com",
    phone: "0901234568",
    avatar: "",
    permission: "Bật",
    role: "guest",
    status: true,
  },
  {
    id: 3,
    username: "admin3",
    password: "admin",
    fullName: "Nguyễn Văn C",
    email: "nvc@gmail.com",
    phone: "0901234569",
    avatar: "",
    permission: "Tắt",
    role: "guest",
    status: true,
  },
];
