export const dataNavigation = [
  {
    id: "Cat1",
    name: "Danh mục cấp 1",
    icon: '<i class="ri-mail-line"></i>',
  },
  {
    id: "Cat2",
    name: "Danh mục cấp 2",
    icon: '<i class="ri-mail-add-line"></i>',
  },
  {
    id: "Cat3",
    name: "Danh mục cấp 3",
    icon: '<i class="ri-mail-star-line"></i>',
  },
  {
    id: "Cat4",
    name: "Danh sách bài viết",
    icon: '<i class="ri-markup-line"></i>',
  },
  {
    id: "Cat5",
    name: "Danh sách sản phẩm",
    icon: '<i class="ri-shapes-line"></i>',
  },
  {
    id: "Cat6",
    name: "Lịch hẹn",
    icon: '<i class="ri-calendar-2-line"></i>',
  },
  {
    id: "Cat7",
    name: "Bình luận",
    icon: '<i class="ri-chat-3-line"></i>',
  },
];

export const dataList = [
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
];

export const dataListAccount: iAccountAuth[] = [
  {
    fullName: "admin1",
    email: "admin1@gmail.com",
    phone: "0987385477",
    status: true,
    role: "admin",
    avatar: "",
    slug: "admin1-1695974558895",
  },
  {
    fullName: "Nguyễn Hoàng Phúc",
    email: "phucnh2808@gmail.com",
    phone: "0906391823",
    status: true,
    role: "employee",
    avatar: "",
    slug: "nguyen-hoang-phuc-1696661664507",
  },
  {
    fullName: "Phạm Minh Thành",
    email: "thanhpm@gmail.com",
    phone: "0902232233",
    status: true,
    role: "employee",
    avatar: "",
    slug: "pham-minh-thanh-1696661870035",
  },
  {
    fullName: "Lê Văn Sơn",
    email: "sonlv@gmail.com",
    phone: "0904564567",
    status: true,
    role: "employee",
    avatar: "",
    slug: "le-van-son-1696661914270",
  },
];
