export const dataNavigation = [
  {
    id: "tableCategoryLevel1",
    name: "Danh mục cấp 1",
    icon: '<i class="ri-mail-line"></i>',
  },
  {
    id: "tableCategoryLevel2",
    name: "Danh mục cấp 2",
    icon: '<i class="ri-mail-add-line"></i>',
  },
  {
    id: "tableCategoryLevel3",
    name: "Danh mục cấp 3",
    icon: '<i class="ri-mail-star-line"></i>',
  },
  {
    id: "listPosts",
    name: "Danh sách bài viết",
    icon: '<i class="ri-markup-line"></i>',
  },
  {
    id: "listProducts",
    name: "Danh sách sản phẩm",
    icon: '<i class="ri-shapes-line"></i>',
  },
  {
    id: "appointmentSchedule",
    name: "Lịch hẹn",
    icon: '<i class="ri-calendar-2-line"></i>',
  },
  {
    id: "comments",
    name: "Bình luận",
    icon: '<i class="ri-chat-3-line"></i>',
  },
];

export const dataList = [
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: false,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
  {
    id: "1",
    imgUrl: "",
    name: "Nguyễn Hoàng Phúc",
    category: "Trắng da",
    dateTime: "10/10/2010",
    permission: true,
  },
];
